### ISSUE TITLE
COPD relative rate of death calibration

### ISSUE THREAD

**Issue by mnjowe** [UCL/TLOmodel#1085]
In COPD calibration, in order for us to compute the rate of (**all cause**) death according to COPD stage (none, mild, moderate, severe + v severe), we would want to log each individual death by lung function. This information is available in the "detailed" demography logger (which captures the full state of each person at the point of death, but it needs to be turned on using `custom_logs`.

<img width="737" alt="image" src="https://github.com/UCL/TLOmodel/assets/39991060/a7ce4161-c83d-4219-8385-4b32d2d5bce5">

This would be achieved by elaborating the code already established which erroneously (@tbhallett's fault!) computes Copd death rates rather than all-cause death rates by COPD stage. [https://github.com/UCL/TLOmodel/blob/0ce8d992f6e07afed398cb3d99468abb7491cc4d/src/scripts/copd_analyses/copd_calibrations.py#L105]

**Comment by mnjowe** [comment]
@andrew-phillips-1 and @tbhallett . I was wondering if we have agreed on what should be  the denominator for plotting rate and relative rate of deaths(all causes)?

**Comment by andrew-phillips-1** [comment]
Hi @mnjowe  
If you would like to see how a rate is calculated you can see on this video.
https://www.youtube.com/watch?v=XPbYtCgKoMA&ab_channel=AndrewPhillips

But it is close enough to calculate the death rate over an x year period as 
number of deaths in the x years in the age range / number of people living in that age range at the start of the x years

For the relative rate, we calculate this separate for a group a people in a given lung-function category and then divide it by the rate for a "reference" lung-function category, so that it becomes a relative rate, i.e. what the rate is relative to that for people in a reference lung function category.     

Does this help ?

**Comment by mnjowe** [comment]
Yes @andrew-phillips-1 it does help. Thanks for the video, I find both part 1 and part 2 very helpful.

**Comment by mnjowe** [comment]
Hi @andrew-phillips-1 and @tbhallett . Kindly find attached calibrations for rate of death and relative rate of deaths as discussed in our epi call. You may also be interested in the [code here](https://github.com/UCL/TLOmodel/pull/1087/commits/6507393046fde14457c746ee929ba59ba97889d8)

For rate of deaths(modal) results

            none           0.043594
            mild           0.612852
            moderate       1.979928
            severe         3.318468
            very_severe    5.596724

Relative rate of deaths(model) results 
            
            none             1.000000
            mild            14.058054
            moderate        45.417054
            severe          76.121477
            very_severe    128.381801

![image](https://github.com/UCL/TLOmodel/assets/32415622/250fd973-21f2-42cd-b12e-e109aac31ac4)

![image](https://github.com/UCL/TLOmodel/assets/32415622/81c886af-3af5-4d37-b2b0-d5bb8cacae9a)

**Comment by mnjowe** [comment]
What else can we add to the relative deaths legend? is `model` and `data` enough?

**Comment by andrew-phillips-1** [comment]
Hi @mnjowe   Death rates compared with Alupo data look good.  I thought our model death rates would be lower.  I think OK to have model and data as the legend.  I would add a mention of "data are from Alupo et al" somewhere to the figure legend.

For the relative rate compared with Mannino et al.  I am surprised at how high the relative rate for all cause mortality is for severe and very severe lung function in our model.  Those with lung function >= 5 obviously tend to be much older than the average of the over 30 year olds, but the figures we are comparing with from Mannino et all are also not adjusted for age.  If we lower the risk of COPD death at lung function levels 5 and 6 this will take us further from the GBD figures.

**Comment by tbhallett** [comment]
Well done Emmanuel!

**Comment by mnjowe** [comment]
Thanks @tbhallett.  @andrew-phillips-1 I agree that the numbers for relative rate all cause mortality  are high for severe and very severe. is there anything we can do?

**Comment by andrew-phillips-1** [comment]
Hi @mnjowe 
In the observed data they assessed risk of death over 22 years.  They had about 20% with severe COPD surviving 20 years, while our death rates from COPD for people in this category are much higher.   If we lower our exacerbation rate or death rate in people with severe/very severe COPD then we move further away from the GBD numbers.  So I don't think it is clear what to do, which data to prioritise fitting to.  Do you have any thoughts ?

**Comment by mnjowe** [comment]
I agree to your thoughts @andrew-phillips-1. I was thinking that if we increase the death risk in lung function category 0, it can make some difference to the relative rate graph as we are dividing death risk in all other lung function categories by death risk in lung function category 0?

**Comment by andrew-phillips-1** [comment]
Hi @mnjowe That would reduce the relative rate I agree, but I don't think we can have a death risk from COPD at lung function level 0.  Then that means adjusting the death risk from other diseases in other modules that we don't have responsibility for.

**Comment by mnjowe** [comment]
Yea, you're right @andrew-phillips-1.
