### ISSUE TITLE
actual_appt_footprint of HSI_Tb_Xray_level2 in conflict with mode_appt_constraints = 2

### ISSUE THREAD

**Issue by marghe-molaro** [UCL/TLOmodel#1090]
In HSI_Tb_Xray_level2, if consumables are not available the HSI defaults to a clinical diagnosis, with adds another clinical appt footprint ("Under5OPD" : 1) to the expected one. Under5OPD relies on different medical officers than the expected_appt_footprint ("DiagRadio": 1);  an issue in mode_appt_constraints = 2 therefore occurs when capabilities for the officers required for the Under5OPD have already been exhausted before the HSI is ran, since we cannot know that those officers would be required until the HSI is actually ran. This is what leads to issue #1089.

There are two possible solutions:
1. Since this seems to be quite an infrequent occurrence (~3 times a month in a 50,000 population according to analysis in #1089, although this would depend on prioritisation policy) we could ignore the exhausted capabilities issue for the particular instance of the Under5OPD appt for this HSI.
2. For the specific case of HSI_Tb_Xray_level2, when checking if capabilities are still available we can, in addition to capabilities required for the expected_footprint, check whether there are also capabilities for an Under5OPD appt, whether those would actually be required when running the event or not.
3. Modify the HSI s.t. instead of simply adding the Under5OPD footprint, an additional clinical HSI is scheduled.

@tdm32, what would you recommend?

**Comment by tdm32** [comment]
Hi @marghe-molaro, thanks for flagging this. 

I suppose if the consumables are not available for xray we should amend the footprint to be blank as the DiagRadio appt will not occur. I think what would likely happen is that they are referred back for a clinical diagnosis which would require another under5OPD. We might need to write a separate clinical HSI for this though as we don't need them to go through the whole triage process plus HIV testing in HSI_Tb_ScreeningAndRefer. It could even be a 0.5 Under5OPD appt with a pharmacy appt attached. 

I can do this as a separate PR if helpful?

**Comment by marghe-molaro** [comment]
Hi @tdm32, I think a separate clinical HSI would fix this issue quite nicely, as it would require no "compromise" with the mode_appt_constraints assumptions (since we can check that all required officers are available to perform this clinical HSI before it is actually ran). A separate PR would be perfect, thank you!

**Comment by tdm32** [comment]
@marghe-molaro I'm on it :-) 

Just a note to add the priority ranking for the new treatment id - if you're happy to do that. I don't want to mess with your system.

**Comment by marghe-molaro** [comment]
Thank you so much @tdm32! We've actually added a new "safety feature" which checks that all Treatment_IDs are included in the policies before PRs can be submitted, so when you add the new treatment id you should - hopefully! - see the test_all_treatment_ids_defined_in_priority_policies test failing. But if you submit the PR anyway I will make sure to modify the policies accordingly and resolve that error. Check I just check with you - I guess the priority we would assign to the new HSI should be the same as the original one?

**Comment by tdm32** [comment]
@marghe-molaro Yes keep the same priority for this, it's just another step in the TB diagnostic triage. Thanks Margherita!
