### ISSUE TITLE
Conditionally run `set-variables` job in `run-profiling.yaml` workflow file

### ISSUE THREAD

**Issue by matt-graham** [UCL/TLOmodel#1123]
At the moment the `set-variables` job in `.github/workflows/run-profiling.yaml` runs unconditionally:

https://github.com/UCL/TLOmodel/blob/b9e157f9562c2fdcd0115bb01c076d8a759d432c/.github/workflows/run-profiling.yaml#L31-L46

which means even if the subsequent steps are skipped we get a workflow success status rather than skipped status, which for example stops us using a query like https://github.com/UCL/TLOmodel/actions/workflows/run-profiling.yaml?query=is%3Asuccess to find successful runs of the workflow (or at least ones in which any profiling was performed!). 

I think if we add an `if` condition something like

```yaml
if: (github.event_name != 'issue_comment') || ((github.event_name == 'issue_comment') && (github.event.comment.body == '/run profiling')
```

we should prevent the job being run when the succeeding jobs will be skipped, though then we do end up needing to keep the condition here in sync with the logic in the next jobs.

**Comment by willGraham01** [comment]
I feel like the `if` condition is the lesser of two evils - the alternative (which I think we tried when first setting up the profiling) is to put all of the logic in the `run-profiling` workflow into the `command` argument to the comment-triggered stuff, which wasn't the most readable.
