### ISSUE TITLE
displayed a smaller number of characters than we use per line

### ISSUE THREAD

**Issue by EvaJanouskova** [UCL/TLOmodel#1175]
A smaller number of characters than what we use per line is displayed in the documentation. Could be the entire lines displayed there?

Here is an example where I noticed this:
https://www.tlomodel.org/_modules/tlo/methods/contraception.html#StartInterventions

**Comment by matt-graham** [comment]
At the moment it is possible to see the entire line in fixed width content like the source code but it is a bit of a pain to do so as you have to manually drag to the right by selecting text, or scroll to the bottom of the content and use the horizontal scroll bar there.

To fix this, we would either need to make the font size smaller in `pre` elements used to display code or make the whole content column wider. From a readability perspective probably the latter is better? If so will need to add some custom CSS like the following

```css
@media screen and (min-width: 1280px) {
  div.wy-nav-content {
    max-width: 960px;
  }
}
```

which should make sure this only applies on screens with sufficient width to not need horizontal scroll bars (side navigation column is 320px wide), in a file under `docs/_static`, for example similar to [the `docs/_static/theme_overrides.css` that was recently removed](https://github.com/UCL/TLOmodel/blob/b04fafde5c0ad29c881d4cc34ce9f530e59d73f0/docs/_static/theme_overrides.css) and some content in `conf.py` similar to

https://github.com/UCL/TLOmodel/blob/b04fafde5c0ad29c881d4cc34ce9f530e59d73f0/docs/conf.py#L71-L75
