### ISSUE TITLE
Check consistency of population-wide HSI events assumptions

### ISSUE THREAD

**Issue by marghe-molaro** [UCL/TLOmodel#1260]
Currently in mode 2 we do not enforce resource constraints on population-wide HSI events as no modules in the simulation at the time of mode 2 development employed population-wide HSI events. The current healthcare system set up however still allows for this possibility, meaning developers may introduce population-wide HSI events in the future. For consistency, we should either 1. remove population-wide HSI events completely from the simulation, or 2. Allow for the possibility of population-wide HSI events to be resource constrained (both by HR capabilities and equipment). 

@tbhallett @EvaJanouskova

**Comment by tbhallett** [comment]
Good point. It would make life most easy if we got rid of population wide HSI.

**Comment by EvaJanouskova** [comment]
Thank you, @marghe-molaro, this answers my question well. @tbhallett, does this mean that for now I can only check the essential equipment availability for individual-level HSI events and if it's not available prevent the event from running; and leave the checking of equip availability for population-wide HSI events to be addressed as part of this issue?

**Comment by tbhallett** [comment]
> Thank you, @marghe-molaro, this answers my question well. @tbhallett, does this mean that for now I can only check the essential equipment availability for individual-level HSI events and if it's not available prevent the event from running; and leave the checking of equip availability for population-wide HSI events to be addressed as part of this issue?

Yes, I think so.
