### ISSUE TITLE
Individual-based modelling learning resources

### ISSUE THREAD

**Issue by tbhallett** [UCL/TLOmodel#1281]
@andrew-phillips-1  and Loveleeen have created a set of excellent course materials for learning individual-bases modelling:

https://docs.google.com/document/d/1fH0qKeLpvSRBNEePDYS9eaet4qJCQBOvr9kbJlyJVq4/edit#

@andrew-phillips-1  --- do you think we could present this content (with due attrribution of course) on our [webpag](https://www.tlomodel.org/background.html)...

**Comment by andrew-phillips-1** [comment]
Thanks.  Yes, of course.  This is intended to be freely available to anyone.
