### ISSUE TITLE
`HealthSystemChangeParameters` event has no effect when asked to update `BedDays` policy

### ISSUE THREAD

**Issue by willGraham01** [UCL/TLOmodel#1346]
When the `HealthSystemChangeParameters` event is called/scheduled to update the behaviour of the bed-days allocations, it does not change the behaviour of the bed-days allocations in the `HealthSystem`. 

The `HealthSystemChangeParameters` event which changes the availability of bed days [currently changes the `BedDays.availability` property](https://github.com/UCL/TLOmodel/blob/3bdba8c47bd6124719d75c0be4c20718d22a56ac/src/tlo/methods/healthsystem.py#L2675) when it runs:
- The `BedDays.availability` value is only used by the `BedDays` class in [`set_scaled_capacity`](https://github.com/UCL/TLOmodel/blob/3bdba8c47bd6124719d75c0be4c20718d22a56ac/src/tlo/methods/bed_days.py#L104)
- `set_scaled_capacity` itself is only used in the [`initialise_beddays_tracker`](https://github.com/UCL/TLOmodel/blob/3bdba8c47bd6124719d75c0be4c20718d22a56ac/src/tlo/methods/bed_days.py#L119) method.
- `initialise_beddays_tracker` is only called once in the initial setup of the simulation (specifically in the `initialise_simulation` step for each module).

As such, changing the `BedDays.availability` property when an event fires _after_ the simulation begins has no effect.

If we really only need to set the properties of the BedDays tracker before the simulation, we don't need an event to handle changing them. Otherwise, presumably the correct action that should be taken is that the `availability` property should be updated, and the internal trackers for maximum capacities should also be updated? This might lead to issues with the current and forecast allocations though (since EG setting the availability to 0 will mean that any currently scheduled occupancies have to end).

If anyone knows what the intended behaviour is meant to be (or whether we need this feature at all), advice would be appreciated!

**Comment by tamuri** [comment]
Ping @tbhallett

**Comment by tbhallett** [comment]
Thanks for spotting this, @willGraham01 

The _intended_ behaviour is that, mid-way through a simulation, the total numbers of bed available can be changed (either up or down).

So, I agree with you that this is a bug.

**Comment by tbhallett** [comment]
We let them stay. They will eventually be discharged and then we accept no others.

Sent from Outlook for iOS<https://aka.ms/o0ukef>
________________________________
