### ISSUE TITLE
Over-writing of `post_apply_hook` by some `HSI_Events`

### ISSUE THREAD

**Issue by tbhallett** [UCL/TLOmodel#1360]
There are some instance of disease module writing instances of `HSI_Events` with a `post_apply_hook` method defined. This will over-write the method of the same name in the base class, preventing the functionality contained therein to operate ([post_apply_hook in HSI_Event base class](https://github.com/UCL/TLOmodel/blob/67c80589a2e0f274ac12c87cd76876df3010d51d/src/tlo/methods/hsi_event.py#L174)). It was a sort of "unwritten rule" (!) that the `post_apply_hook` part of an HSI_Event is reserved for use by the HSI_Event itself.

Examples of HSI_Event instance over-writing this method are:
https://github.com/UCL/TLOmodel/blob/67c80589a2e0f274ac12c87cd76876df3010d51d/src/tlo/methods/tb.py#L2236
https://github.com/UCL/TLOmodel/blob/67c80589a2e0f274ac12c87cd76876df3010d51d/src/tlo/methods/contraception.py#L1215

There may be others...!

A simple fix would be for this logic to be placed at the end of the `apply` function in the respective HSI_Event.

But, a better fix would be allow the disease module do over-write the `post_apply_hook` method and create another method that is only called by the HealthSystem. e.g. in the `HSI_Event` base class:
* put the current content of the `post_apply_hook` into `_run_after_hsi_event`,
* over-write run (from the Event base class) to run `apply`, then `post_apply_hook`, then `_run_after_hsi_event`

**Comment by matt-graham** [comment]
Another option would be for any classes which do overwrite the base class implementation of `post_apply_hook` to have to call the base class implementation within their implementation using

```Python
    super().post_apply_hook()
```

Overall though I think your proposed approach @tbhallett of creating a new 'private' method `_run_after_hsi_event` is probably nicer as it doesn't rely on people remembering to call the base class method in their implementation.

**Comment by tbhallett** [comment]
Thanks Matt. I'll give it a go
