### ISSUE TITLE
Create repository of consumables and modelled interventions

### ISSUE THREAD

**Issue by sakshimohan** [UCL/TLOmodel#1364]
Following Jo's suggestion:

> I am also wondering if we want to have some kind of central repository which details each of the modelled interventions, the drugs being used, the assumed dose and the source. I know people will likely have things like this in their right up but it might be worth formalising this - especially as i've noticed there is some discrepancy with what is in the some modules and whats recommended in the most recent STG (2023).

We might also want to add equipment to this and have a comprehensive repository of resources (other than HR) required by each interventions. Eventually, we might want modules to extract quantities from here rather than have those hard coded.

**Comment by joehcollins** [comment]
Thanks for creating Sakshi! I'll think on what form this might take

**Comment by tbhallett** [comment]
Links to #1339

**Comment by tbhallett** [comment]
Closing in favour of #1368
