### ISSUE TITLE
website - link to profile page

### ISSUE THREAD

**Issue by EvaJanouskova** [UCL/TLOmodel#1393]
Could you please add link to my profile page on the [tlo](https://www.tlomodel.org/contributors.html) website?

Here is the link: https://profiles.ucl.ac.uk/90260

Thank you!

**Comment by tamuri** [comment]
You can raise a PR adding `website` entry to your entry in `contributors.yaml` - [https://github.com/UCL/TLOmodel/blob/27291aefc5afc4ef943b4786b182c490c0b0a9c4/contributors.yaml#L195](https://github.com/UCL/TLOmodel/blob/27291aefc5afc4ef943b4786b182c490c0b0a9c4/contributors.yaml#L195)

**Comment by tbhallett** [comment]
@EvaJanouskova  - do you want to do this PR?

**Comment by EvaJanouskova** [comment]
@tbhallett - Yes, thank you for reminding me.
