### ISSUE TITLE
use of xlsx

### ISSUE THREAD

**Issue by EvaJanouskova** [UCL/TLOmodel#1432]
Couldn't we stop using xlsx, rather have each sheet in separate csv file and if we need to tight them together put them in the same folder?

It makes it much more difficult to merge master into a branch if there are changes in an xlsx file from both sides.

**Comment by tamuri** [comment]
Thanks, Eva - that's what Emmanuel was discussing at today's meeting. See #1337 and PR #1432

**Comment by EvaJanouskova** [comment]
Ahh, brilliant, thanks!
