### ISSUE TITLE
New consumables scenarios not modifying consumables availability using existing cons_availability_postSwitch

### ISSUE THREAD

**Issue by tdm32** [UCL/TLOmodel#1497]
The new scenarios for consumables availability work well if set at initialisation, however they are not switching consumables availability correctly when using cons_availability_postSwitch. The initial cons availability remains throughout the full simulation. 

Note, existing scenarios all_vital_available, all_medicines_available etc do work with the switch.

This is the working branch for the GF and FCDO scenarios:
https://github.com/UCL/TLOmodel/tree/tara/gf_hss_and_htm_scale_up

In tests/test_consumables.py, there is a new test (test_check_consumables_modified_correctly) which initially sets the consumables availability to 'none', then switches it to scenario6 (all consumables at or above 75th percentile).

Currently, the final assertion fails. This is because after the switch, the consumables availability is still set to 'none'.

Once the consumables scenarios are correctly modifying availability, we expect this test to pass. 

PR #1495 (https://github.com/UCL/TLOmodel/pull/1495) originally proposed a fix for this which has already been merged into this working branch.

**Comment by tbhallett** [comment]
pushed fix.
