### ISSUE TITLE
Consumables consumption double-counting

### ISSUE THREAD

**Issue by tbhallett** [UCL/TLOmodel#1505]
Are we over-counting use of consumables in the following scenario (common in contraception module)....

1- HSI runs, requests consumables A and B. A is available, B is not. Consumption of B is logged.
2- HSI not successful so is rescheduled.
3- HSI runs again and request consumables A and B. Consumption of A and B is logged.

Thus, we have counted use of B twice, when in fact the delivery of the service requires only one item of A and one item of B.

We could overcome this by making the initial check without there being any logging, and only logging usage if all (essential) available (when the service is actually provided).

(cc @sakshimohan )

**Comment by tbhallett** [comment]
@EvaJanouskova  -- what do you think about this?

**Comment by EvaJanouskova** [comment]
@tbhallett,It depends on what information you need to store. If you are only interested in usages, then this is the correct solution. However, the ‘not available’ group loses its meaning, as you will only have information about missing non-essential items. If the idea is to know how often something is missing, we will need to consider a different solution to store all information: availability when requested, and usages for all items (both essential and non-essential).

**Comment by sakshimohan** [comment]
For the purposes of costing, only logging usage if all (essential) available (when the service is actually provided) would work best. 

Previously, we have looked at the number of instances of a consumable not being available by HSI to get a picture of which consumables stock-outs are most disruptive. See figures below. This is less essential than the costing use case but does add some depth to any analysis on scenarios of consumable availability. 

![Image](https://github.com/user-attachments/assets/46d9cf00-3d91-47c9-b33b-f1de7d50ae37)
![Image](https://github.com/user-attachments/assets/08fad429-1989-478c-8750-e58c8190a482)

Is it possible to log the number of times the consumable was **unavailable** as done previously, and add - 
1. number of times a consumable was **requested**
2. number of times a consumable was **used** when a service was provided

**Comment by EvaJanouskova** [comment]
you could log 3 categories instead of just two: available_used x available_not_used x not_available

**Comment by tbhallett** [comment]
We already have an option `to_log` which is of type `bool`. If it's False (it defaults to True) then a query is made about availability and the result returned but there is no logging. We could log these queries.

For the specific case of Consumales though, I think a relatively simple fix would be just to adapt the logic slightly:

1- check if all essential consumables available (with `to_log=False`)
2- if not available, resceulde HSI; 
3- if available, make the request again (with `to_log=True`)

@EvaJanouskova  -- ignoring the wider issues for now, would you be able to make that little fix to the Contraceptive module?

**Comment by tbhallett** [comment]
> By wider issue, you mean, ignore that this is general issue for all modules and fix it only for Contraceptive module?

Yes, exactly. Would that be possible in a very small PR?

**Comment by sakshimohan** [comment]
Thanks, @tbhallett and @EvaJanouskova. I'm also concerned about the logging of epilepsy consumables which seem to form a large chunk of the consumables budget and whose dispensed quantity logged reduces with improvement in consumable availability. Any chance you could take a look at those as well?
I've seen that the quantity per HSI specified makes sense.

**Comment by EvaJanouskova** [comment]
@tbhallett, Not sure if such a hack should be merged into master, though. @tamuri, should we keep the temporary hack in Sakshi’s branch and ensure it is done properly before it’s merged into master? Or is it okay to merge these changes into master and open an issue for this to be fixed properly in the future?

**Comment by EvaJanouskova** [comment]
> Thanks, [@tbhallett](https://github.com/tbhallett) and [@EvaJanouskova](https://github.com/EvaJanouskova). I'm also concerned about the logging of epilepsy consumables which seem to form a large chunk of the consumables budget and whose dispensed quantity logged reduces with improvement in consumable availability. Any chance you could take a look at those as well? I've seen that the quantity per HSI specified makes sense.

The `epilepsy` module is under Joe’s supervision. @joehcollins, do you prefer to handle this, or would you like me to take care of it?

**Comment by tbhallett** [comment]
@EvaJanouskova  - I don't think it's a hack.  I see it that the functionality is already there to check consumables availability without usage being logged, we just need to use it.

**Comment by EvaJanouskova** [comment]
@tbhallett, It is a hack in the sense that if we do this, especially if we do it only in two modules:
1. the available items logged may still include some unused items from other modules, and
2. not available items will also be logged inconsistently. Within these two modules, they will only be logged as not available in cases where they are non-essential and all essential items are available. In the other modules, both essential and non-essential items will be logged as not available whenever they are requested.

**Comment by joehcollins** [comment]
> > Thanks, [@tbhallett](https://github.com/tbhallett) and [@EvaJanouskova](https://github.com/EvaJanouskova). I'm also concerned about the logging of epilepsy consumables which seem to form a large chunk of the consumables budget and whose dispensed quantity logged reduces with improvement in consumable availability. Any chance you could take a look at those as well? I've seen that the quantity per HSI specified makes sense.
> 
> The `epilepsy` module is under Joe’s supervision. [@joehcollins](https://github.com/joehcollins), do you prefer to handle this, or would you like me to take care of it?

I can look at the contraception module

**Comment by sakshimohan** [comment]
> [@tbhallett](https://github.com/tbhallett) [@EvaJanouskova](https://github.com/EvaJanouskova) [@sakshimohan](https://github.com/sakshimohan) - just reflecting on this I would echo Eva's concerns about the inconsistency of using this approach in contraception/epilepsy as I dont think its applied consistently in other module (including mine).
> 
> For example in a labour appointment if a women needed treatment for sepsis which required 2 essential consumables I am currently returning the availability for both A and B and if A or B aren't available the intervention is not delivered (a repeat HSI is not scheduled like other modules however). But that does mean that A or B is being logged as 'used' even if the intervention was not actually delivered? If i'm following...

Thanks both for raising very valid concerns with this quick fix. I agree that a more comprehensive solution would be better But I have to admit that I'm not sure how much work coding a[FCDO_analysis_consumable_cost_discrepancy.xlsx](https://github.com/user-attachments/files/17681874/FCDO_analysis_consumable_cost_discrepancy.xlsx)
 fundamental change to the logging process would take. Just to highlight, the 12 consumables listed below account for >90% of the magnitude of costs under perfect availability of consumables being less than that under default availability. Full list of consumables with this discrepancy in the file attached. 

The columns on the right indicate the cost of consumables dispensed over 11 years under the assumptions of default availability and perfect availability. 

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:////Users/sm2511/Library/Group%20Containers/UBF8T346G9.Office/TemporaryItems/msohtmlclip/clip.htm">
<link rel=File-List
href="file:////Users/sm2511/Library/Group%20Containers/UBF8T346G9.Office/TemporaryItems/msohtmlclip/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">


Item_code | cost_of_consumables_dispensed | Default availability | Perfect availability
-- | -- | -- | --
276 | Carbamazepine 200mg_1000_CMST | 356,581,805 | -
10 | Trocar | 312,252,208 | 8,543,771
20 | Suture, catgut, chromic, 0, 150 cm | 110,286,433 | 2,656,017
12 | Jadelle (implant), box of 2_CMST | 106,251,067 | 2,225,528
8 | Lidocaine HCl (in dextrose 7.5%), ampoule 2 ml | 103,340,740 | 6,641,941
279 | Phenytoin sodium 100mg_1000_CMST | 64,208,514 | -
19 | Needle, suture, assorted sizes, round body | 59,138,101 | 1,424,217
3 | Depot-Medroxyprogesterone Acetate 150 mg - 3 monthly | 49,771,483 | 10,560,688
81 | Ceftriaxone 1g, PFR_each_CMST | 68,202,032 | 33,897,808
98 | Water for injection, 10ml_Each_CMST | 29,709,663 | 5,958,128
21 | Tape, adhesive, 2.5 cm wide, zinc oxide, 5 m roll | 24,561,504 | 1,095,044
11 | Needle suture intestinal round bodied A circle trocar_6_CMST | 16,381,285 | 1,337,398



</body>

</html>

**Comment by joehcollins** [comment]
@tbhallett - just seen PR #1511 mentioned above. Do you want me to wait for this to be reviewed/go in before doing anything with the cons logging described here? if not i can look at this tomorrow

**Comment by tbhallett** [comment]
> [@tbhallett](https://github.com/tbhallett) - just seen PR [#1511](https://github.com/UCL/TLOmodel/pull/1511) mentioned above. Do you want me to wait for this to be reviewed/go in before doing anything with the cons logging described here? if not i can look at this tomorrow

Thanks very much for the offer, @joehcollins. You'll see in the PRs linked above that Tara has proposed a new and (I think) good approach for dealing with this.

We'd be grateful for your comments on both those. We'd like to get this finalised by the middle of tomorrow so that final runs can hopefully be submitted later that day.

**Comment by joehcollins** [comment]
@tbhallett i will have a look at both today!
