### ISSUE TITLE
Speed up documentation generation

### ISSUE THREAD

**Issue by tamuri** [UCL/TLOmodel#1513]
Improving the time taken to generate the docs would facilitate quicker deployment
Ideas:

- Remove linkcheck as part of doc build because most links are behind paywall and so fail the check (and, we're not actively checking these)
- Instead of generating tables from the resource files, integrate and use an online viewer ([example](https://www.getgrist.com/csv-viewer/)) - this would work for all files that are in CSV format.
- Sphinx seems to be regenerating html files for unchanged source files. Not sure why.

**Comment by tamuri** [comment]
~Not sure why.~

- Remove `-f` argument for sphinx-apidoc
- Remove `{postargs:-E}` for sphinx-build

**Comment by matt-graham** [comment]
Other than online viewer which now has a separate issue (#1526) the remainder of this was resolved by #1525
