### ISSUE TITLE
stunting---wasting interaction

### ISSUE THREAD

**Issue by EvaJanouskova** [UCL/TLOmodel#1533]
@tbhallett, @timcolbourn, I'm looking at the _stunting_ module to figure out what the interaction with _wasting_ module is. There are 2 parameters related to wasting: `rr_stunting_prior_wasting`: Relative risk of stunting if prior wasting in the last 3 months, and `rr_progress_severe_stunting_if_prior_wasting`: Relative risk of severe stunting if previously wasted.

However, what seems odd to me is that these are used if predictor `un_ever_wasted` is True. This property is True if WHZ was ever lower than -2. As these relative risks are called "prior wasting", shouldn't they be used when `un_ever_wasted` is False?

----
Another question is whether the predictor is defined as it is meant to be---as "ever having lower WHZ", or should it be "ever having acute malnutrition (MAM or SAM)"?

---

Lastly, what is meant by the description 'Relative risk of stunting if prior wasting in the **last 3 months**'? The property `un_ever_wasted` only carries information on whether they were **ever** wasted, no way to say if it applies to last 3 months or not.

**Comment by timcolbourn** [comment]
>However, what seems odd to me is that these are used if predictor un_ever_wasted is True. This property is True if WHZ was ever lower than -2. As these relative risks are called "prior wasting", shouldn't they be used when un_ever_wasted is False?

True seems correct to me if it means WHZ was ever lower than -2  given that means if they were ever wasted?


> Another question is whether the predictor is defined as it is meant to be---as "ever having lower WHZ", or should it be "ever having acute malnutrition (MAM or SAM)"?

You could rename it to "ever having WHZ <-2" if that's more intuitive - either way I think the definition is the same?


> Lastly, what is meant by the description 'Relative risk of stunting if prior wasting in the **last 3 months**'? The property `un_ever_wasted` only carries information on whether they were **ever** wasted, no way to say if it applies to last 3 months or not.

Yes that seems incorrect - I'm guessing the paper Ines used to determine the rr was for "past 3 months"? but it could be "ever" - I think that's fine, given stunting is chronic and there is probably an increased risk even if you were wasted more than 3 months ago? what do the references Ines cites in her methods write-up say?

**Comment by EvaJanouskova** [comment]
> > However, what seems odd to me is that these are used if predictor un_ever_wasted is True. This property is True if WHZ was ever lower than -2. As these relative risks are called "prior wasting", shouldn't they be used when un_ever_wasted is False?
> 
> True seems correct to me if it means WHZ was ever lower than -2 given that means if they were ever wasted?

Yes, thank you, you're right. I concentrated on `rr_stunting_prior_wasting`, which sounded to me like the relative risk of stunting happening prior to ever being wasted, but from the rest, it was actually meant as the relative risk of stunting (progress) if they happened to be ever wasted before. So yes, this is fine.

> > Another question is whether the predictor is defined as it is meant to be---as "ever having lower WHZ", or should it be "ever having acute malnutrition (MAM or SAM)"?
> 
> You could rename it to "ever having WHZ <-2" if that's more intuitive - either way I think the definition is the same?

What I was asking here is if that is what you wanted. Should the relative risk be higher if WHZ < -2, but not if they had MAM/SAM while having normal WHZ? From reading the reference, it seems that they indeed only predicted stunting based on wasting (WHZ), not acute malnutrition. It's okay then.

> > Lastly, what is meant by the description 'Relative risk of stunting if prior wasting in the **last 3 months**'? The property `un_ever_wasted` only carries information on whether they were **ever** wasted, no way to say if it applies to last 3 months or not.
> 
> Yes that seems incorrect - I'm guessing the paper Ines used to determine the rr was for "past 3 months"? but it could be "ever" - I think that's fine, given stunting is chronic and there is probably an increased risk even if you were wasted more than 3 months ago? what do the references Ines cites in her methods write-up say? 

Yes, the associations between stunting<->wasting were calculated in 2 consecutive periods; that is what she likely meant (though it would be 2-6 months as they did the measurements monthly in the 1st year, and every 3 months thereafter). I think we can use it as if ever wasted. But it is interesting that you have chosen to use this as a predictor when the relative risk is 1.93, but didn't use it as a predictor if they were ever stunted, for that had a relative risk of 9.50.

**Comment by timcolbourn** [comment]
>But it is interesting that you have chosen to use this as a predictor when the relative risk is 1.93, but didn't use it as a predictor if they were ever stunted, for that had a relative risk of 9.50. Do you recall why?

I think the stunting module remaining unfinished is probably the explanation.

**Comment by EvaJanouskova** [comment]
Thanks for clarifications, I'm closing the issue.
