### ISSUE TITLE
Directly reading parameter values from resource file and comparing them with simulation values

### ISSUE THREAD

**Issue by mnjowe** [UCL/TLOmodel#1540]
In some few parts of the model, parameter values are directly read from resource files (i.e., not using `load_parameters_from_dataframe`) and compared to simulation parameter values. This approach worked with read_excel but has become problematic since the Excel files were converted to CSV and read using `pd.read_csv`. The `pd.read_csv` function handles columns with mixed data types (as is common in parameter columns) by defaulting to the object data type. Consequently, numeric values and other data types are often interpreted as strings.

This behaviour has led to test failures, as assert statements are raising errors due to comparisons between values of specific data types with strings(output from pd.read_csv).

**Comment by tamuri** [comment]
Could we use the `dtypes` argument in `pd.read_excel` for this i.e. in these specific cases, we specify the types of each of the columns (rather than inferrubg, which could be flaky)

**Comment by tamuri** [comment]
Some ruff checks failing

```
check: commands[3]> ruff check src tests
src/tlo/util.py:548:8: E721 Use `is` and `is not` for type comparisons, or `isinstance()` for isinstance checks
    |
546 |     """
547 |     # if value is not a string then return value
548 |     if type(value) != str:
    |        ^^^^^^^^^^^^^^^^^^ E721
549 |         return value
    |

src/tlo/util.py:565:26: F821 Undefined name `ast`
    |
563 |             # Check if it's a list using `ast.literal_eval`
564 |             try:
565 |                 parsed = ast.literal_eval(value)
    |                          ^^^ F821
566 |                 if isinstance(parsed, list):
567 |                     return parsed
    |

```

**Comment by tamuri** [comment]
Probably worth adding some tests

**Comment by mnjowe** [comment]
> Could we use the `dtypes` argument in ~`pd.read_excel`~ `pd.read_csv` for this i.e. in these specific cases, we specify the types of each of the columns (rather than inferrubg, which could be flaky)

Not sure how that can work Asif as I think assigning `dtypes` argument works well when we want to assign one data type to the whole column. We don't want one data type for all values in this case

**Comment by mnjowe** [comment]
> Probably worth adding some tests

I agree
