### ISSUE TITLE
Tracking profiling run results

### ISSUE THREAD

**Issue by matt-graham** [UCL/TLOmodel#686]
We would like to be able to track how the the timings measured in profiling runs of the `src/scripts/profiling/scale_run.py` script changes as new pull-requests are merged in. This would help identifying when PRs lead to performance regressions and allow us to be more proactive in fixing performance bottlenecks.

Ideally this should be as automated using GitHub Actions workflows. Triggering the workflow on pushes to `master` would give the most detail in terms of giving a direct measurement of the performance differences arising from a particular PR, but when lots of PRs are going in could potentially create a large backlog of profiling runs, so an alternative would be to run on a schedule (for example nightly) using the `cron` event.  It would probably be worth also allowing triggering either using the `workflow_dispatch` event or using the comment-triggered workflow functionality to allow manually triggering in PRs that it is thought might have a significant effect on performance before merging.

Key questions to be resolved are what profiling outputs we want to track (for example at what level of granularity, using which profiling tool) and how we want to visualize the outputs. One option would be to [save the profiler output as a workflow artifact](https://docs.github.com/en/actions/using-workflows/storing-workflow-data-as-artifacts). While this would be useful in allowing access to the raw profiling data, the only option for accessing workflow artifacts appears to be downloading the artifact as a compressed zip file so this is not necessarily itself that useful for visualizing the output. One option for visualizing the profiling results would be to use the [GitHub Actions job summary](https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#adding-a-job-summary) which allows using Markdown to produce customized output showed on the job summary page. Another option would be to output the profiling results to HTML files and then [deploy these to either a GitHub Pages site](https://github.com/actions/deploy-pages) or potentially to [a static site on Azure storage](https://learn.microsoft.com/en-us/azure/storage/blobs/storage-blobs-static-site-github-actions?tabs=userlevel).

## Potentially useful links
 
The [airspeed velocity package](https://asv.readthedocs.io/en/stable/) allows tracking the results of benchmarks of Python packages overtime and visualizing the results as plots in a web interface. While focused on suites of benchmarks it does also have support for [running single benchmarks with profiling](https://asv.readthedocs.io/en/stable/commands.html#cmd-asv-profile).

[htmlpreview](https://github.com/htmlpreview/htmlpreview.github.com) allows directly previewing HTML files in a GitHub repository as _GitHub forces them to use the "text/plain" content-type, so they cannot be interpreted_

**Comment by tamuri** [comment]
At some point, we can move the profiling repo into the TLOmodel org (https://github.com/TLOmodel).

**Comment by matt-graham** [comment]
Closing this as profiling workflow now capturing statistics and working reliably
